import socket

# FILE CONTAINING ALL CONFIG RELATED VARIABLES

SOCKET_FAMILY = socket.AF_INET
SOCKET_TYPE = socket.SOCK_STREAM
SERVER_HOST = "localhost"
SERVER_PORT = 3500
SERVER_INCOMING_LIMIT = 1
SERVER_ACCEPT_TIMEOUT = 5

# Bytes
BUFFER_SIZE = 128         